language: php

php:
  - '7.0'
  - '7.1'
  
os: windows

before_script:
  - composer self-update
  - composer install --no-interaction

script: 
  - mkdir -p tests/code-coverage
  - ./vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v
